// Minerals & Rock Classifications for GeoGenesis 3D

export const ROCK_CLASSES = {
  IGNEOUS_EXTRUSIVE: {
    id: 'igneous_extrusive',
    name: 'Igneous (Extrusive)',
    description: 'Formed from rapid cooling of lava at surface or seafloor rifts.',
    color: '#3a3d45'
  },
  IGNEOUS_INTRUSIVE: {
    id: 'igneous_intrusive',
    name: 'Igneous (Intrusive)',
    description: 'Coarse-grained crystalline rock cooled slowly within magma chambers.',
    color: '#bfa482'
  },
  SEDIMENTARY: {
    id: 'sedimentary',
    name: 'Sedimentary',
    description: 'Compacted and cemented mineral particles from hydraulic erosion.',
    color: '#cf9860'
  },
  METAMORPHIC: {
    id: 'metamorphic',
    name: 'Metamorphic',
    description: 'Recrystallized under extreme tectonic shear stress and mantle heat.',
    color: '#8c7b75'
  },
  PRECIOUS_VEIN: {
    id: 'precious_vein',
    name: 'Mineral Vein',
    description: 'Hydrothermal & high-pressure crystalline elements.',
    color: '#ffd700'
  }
};

export const MINERALS = {
  basalt: {
    id: 'basalt',
    name: 'Basalt',
    category: 'IGNEOUS_EXTRUSIVE',
    color: '#2a2d34',
    rgb: [42, 45, 52],
    hardness: 6,
    value: 5,
    researchValue: 2,
    rarity: 'Common',
    idealDepth: [0, 8], // km
    idealTemp: [700, 1200], // °C
    idealPressure: [1, 5], // kbar
    description: 'Dense, dark volcanic rock forming the ocean basins and rift margins.',
    icon: '🪨'
  },
  granite: {
    id: 'granite',
    name: 'Granite',
    category: 'IGNEOUS_INTRUSIVE',
    color: '#c8a68b',
    rgb: [200, 166, 139],
    hardness: 7,
    value: 12,
    researchValue: 5,
    rarity: 'Common',
    idealDepth: [5, 25],
    idealTemp: [600, 950],
    idealPressure: [3, 10],
    description: 'Light-colored intrusive rock with large quartz and feldspar crystals, the buoyant core of continents.',
    icon: '🏔️'
  },
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'IGNEOUS_EXTRUSIVE',
    color: '#1a1829',
    rgb: [26, 24, 41],
    hardness: 5.5,
    value: 28,
    researchValue: 15,
    rarity: 'Uncommon',
    idealDepth: [0, 3],
    idealTemp: [900, 1300],
    idealPressure: [0.5, 2],
    description: 'Volcanic glass quenched instantly from silica-rich rhyolitic lava without crystallization.',
    icon: '🖤'
  },
  sandstone: {
    id: 'sandstone',
    name: 'Sandstone',
    category: 'SEDIMENTARY',
    color: '#d69e64',
    rgb: [214, 158, 100],
    hardness: 4,
    value: 8,
    researchValue: 4,
    rarity: 'Common',
    idealDepth: [0, 5],
    idealTemp: [20, 180],
    idealPressure: [0.1, 2],
    description: 'Stratified clastic sedimentary rock composed of quartz grains deposited by ancient rivers and dunes.',
    icon: '🏜️'
  },
  shale: {
    id: 'shale',
    name: 'Shale',
    category: 'SEDIMENTARY',
    color: '#4e5d6c',
    rgb: [78, 93, 108],
    hardness: 3,
    value: 10,
    researchValue: 6,
    rarity: 'Common',
    idealDepth: [1, 7],
    idealTemp: [50, 220],
    idealPressure: [0.5, 3],
    description: 'Fine-grained laminated sedimentary rock preserving organic carbon and geological epoch boundaries.',
    icon: '📄'
  },
  limestone: {
    id: 'limestone',
    name: 'Limestone',
    category: 'SEDIMENTARY',
    color: '#e0d8c3',
    rgb: [224, 216, 195],
    hardness: 3.5,
    value: 15,
    researchValue: 8,
    rarity: 'Common',
    idealDepth: [0, 4],
    idealTemp: [15, 150],
    idealPressure: [0.1, 2],
    description: 'Carbonate rock formed from accumulated marine skeletal fragments and calcite precipitation.',
    icon: '🐚'
  },
  coal: {
    id: 'coal',
    name: 'Anthracite Coal',
    category: 'SEDIMENTARY',
    color: '#1e1f22',
    rgb: [30, 31, 34],
    hardness: 2.8,
    value: 35,
    researchValue: 12,
    rarity: 'Uncommon',
    idealDepth: [1, 6],
    idealTemp: [80, 250],
    idealPressure: [1, 4],
    description: 'Carbon-rich combustible rock formed from anaerobic decomposition of ancient swamp forests.',
    icon: '⬛'
  },
  marble: {
    id: 'marble',
    name: 'Marble',
    category: 'METAMORPHIC',
    color: '#f2eee9',
    rgb: [242, 238, 233],
    hardness: 4.5,
    value: 45,
    researchValue: 20,
    rarity: 'Uncommon',
    idealDepth: [8, 20],
    idealTemp: [350, 650],
    idealPressure: [4, 9],
    description: 'Non-foliated metamorphic rock created when limestone undergoes intense orogenic heat and recrystallization.',
    icon: '🏛️'
  },
  gneiss: {
    id: 'gneiss',
    name: 'Gneiss',
    category: 'METAMORPHIC',
    color: '#7d6e64',
    rgb: [125, 110, 100],
    hardness: 6.5,
    value: 40,
    researchValue: 22,
    rarity: 'Uncommon',
    idealDepth: [12, 30],
    idealTemp: [550, 850],
    idealPressure: [6, 14],
    description: 'High-grade metamorphic rock displaying distinct alternating bands of light and dark minerals.',
    icon: '〰️'
  },
  quartz: {
    id: 'quartz',
    name: 'Crystalline Quartz',
    category: 'PRECIOUS_VEIN',
    color: '#edf2f7',
    rgb: [237, 242, 247],
    hardness: 7,
    value: 60,
    researchValue: 30,
    rarity: 'Uncommon',
    idealDepth: [3, 15],
    idealTemp: [200, 450],
    idealPressure: [2, 7],
    description: 'Hexagonal silicon dioxide crystals precipitating from deep hydrothermal fluids in fault fractures.',
    icon: '💎'
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Hematite / Iron Band',
    category: 'PRECIOUS_VEIN',
    color: '#9e3d2f',
    rgb: [158, 61, 47],
    hardness: 5.5,
    value: 50,
    researchValue: 25,
    rarity: 'Common',
    idealDepth: [1, 10],
    idealTemp: [100, 400],
    idealPressure: [1, 5],
    description: 'Ancient oxidized banded iron formations created when photosynthetic microbes oxygenated primordial oceans.',
    icon: '⛏️'
  },
  gold: {
    id: 'gold',
    name: 'Native Gold Vein',
    category: 'PRECIOUS_VEIN',
    color: '#ffd700',
    rgb: [255, 215, 0],
    hardness: 2.5,
    value: 250,
    researchValue: 80,
    rarity: 'Rare',
    idealDepth: [4, 18],
    idealTemp: [250, 500],
    idealPressure: [3, 9],
    description: 'Super-heated aqueous hydrothermal veins depositing native gold along seismic shear zones.',
    icon: '🪙'
  },
  lithium: {
    id: 'lithium',
    name: 'Spodumene (Lithium)',
    category: 'PRECIOUS_VEIN',
    color: '#64dfdf',
    rgb: [100, 223, 223],
    hardness: 6.5,
    value: 320,
    researchValue: 120,
    rarity: 'Rare',
    idealDepth: [2, 12],
    idealTemp: [300, 600],
    idealPressure: [2, 8],
    description: 'Rare-element granitic pegmatite enriched in volatile alkali metals, essential for advanced technologies.',
    icon: '🔋'
  },
  diamond: {
    id: 'diamond',
    name: 'Mantle Diamond',
    category: 'PRECIOUS_VEIN',
    color: '#70d6ff',
    rgb: [112, 214, 255],
    hardness: 10,
    value: 1200,
    researchValue: 500,
    rarity: 'Exotic',
    idealDepth: [25, 40],
    idealTemp: [900, 1400],
    idealPressure: [18, 35],
    description: 'Pure carbon crystallized under colossal mantle pressure, blasted upward via supersonic kimberlite pipes.',
    icon: '💠'
  },
  uranium: {
    id: 'uranium',
    name: 'Pitchblende (Uranium)',
    category: 'PRECIOUS_VEIN',
    color: '#39ff14',
    rgb: [57, 255, 20],
    hardness: 5.5,
    value: 1800,
    researchValue: 800,
    rarity: 'Exotic',
    idealDepth: [10, 28],
    idealTemp: [300, 700],
    idealPressure: [5, 15],
    description: 'Radioactive oxide fueling planetary radiogenic mantle convection and geothermal core decay.',
    icon: '☢️'
  }
};
